apiVersion: v1
kind: Service
metadata:
  labels:
    job: go-api
    app: a-service
  name: a-service
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "80"
    prometheus.io/path: "/metrics"

spec:
  ports:
  - name: a-service-port
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: go-service-a-deployment
  type: LoadBalancer

