# 👉 Note: this file is for to test in local environment - nothing to do with k8s

global:
  scrape_interval: 2s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 2s
    static_configs:
      - targets: ['otel-collector:8889']
